### ISSUE TITLE
Supporting case when non cross-account?

### ISSUE THREAD

**Issue by yukihiko-shinoda** [awslabs/aws-config-rdklib#33]
Does this library curently suport only for cross-account? Is there any correct way to use this library in case when non cross-account?

Origin code of this library has `ASSUME_ROLE_MODE` flag:

- [aws-config-rdk/rule_code.py at b42e678ce67eb73432f0787ac1c35ac9a0366b66 · awslabs/aws-config-rdk](https://github.com/awslabs/aws-config-rdk/blob/b42e678ce67eb73432f0787ac1c35ac9a0366b66/rdk/template/runtime/python3.9/rule_code.py#L20)
- [Example AWS Lambda Functions for AWS Config Rules (Python) - AWS Config](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_develop-rules_python-sample.html)

However, this library looks that `ClientFactory` requires assume role:
[aws-config-rdklib/clientfactory.py at ecec699b7e49bc1205f2db9621d8189439392c92 · awslabs/aws-config-rdklib](https://github.com/awslabs/aws-config-rdklib/blob/ecec699b7e49bc1205f2db9621d8189439392c92/rdklib/clientfactory.py#L29)

And, `ClientFactory` is integrated into `Evaluator` (It's instantiated in `handle` function, difficult to replace):
[aws-config-rdklib/evaluator.py at ecec699b7e49bc1205f2db9621d8189439392c92 · awslabs/aws-config-rdklib](https://github.com/awslabs/aws-config-rdklib/blob/ecec699b7e49bc1205f2db9621d8189439392c92/rdklib/evaluator.py#L36)

I'm currently defining child class and overiding above functions.

**Comment by bmorrissirromb** [comment]
I think this was resolved as part of rdklib 0.2.3: https://github.com/awslabs/aws-config-rdklib/pull/36

Now, in rdklib rules, `AssumeRoleMode` is passed as an InputParameters value in the `parameters.json` file.

If `AssumeRoleMode` is true or false, that flag gets passed to the [ClientFactory constructor](https://github.com/awslabs/aws-config-rdklib/blob/281fdcd1a2c6a1ef4e2073a723ef0ab3708784b1/rdklib/clientfactory.py#L18). If `AssumeRoleMode` is false, then the ClientFactory's `build_client` method becomes a simple boto3 client without any `assume_role`.
