### ISSUE TITLE
rdklib lambda layer only attaches for python 3.6

### ISSUE THREAD

**Issue by abaki007** [awslabs/aws-config-rdklib#34]
Hi,

I'm a recent user of rdk and I wanted to avoid use of python 3.6 as it's out of support for AWS boto3 and botocore libraries.
Unfortunately rdk will not attach the rdklib lambda layer to my lambda function if the runtime is not python3.6-lib. rdklib lambda layer supports python 3.6, 3.7, 3.8, 3.9 and therefore should attach to my function.

Steps to replicate:

1. `rdk create YOUR_RULE_NAME --runtime python3.9-lib --maximum-frequency TwentyFour_Hours`
2. install the lambda layer as per: https://aws.amazon.com/blogs/mt/aws-config-rule-development-kit-library-build-and-operate-rules-at-scale/
3. `rdk deploy YOUR_RULE_NAME --rdklib-layer-arn YOUR_RDKLIB_LAYER_ARN`
4. check lambda layers assigned - will find rdklib is not assigned
5. in parameters.json update "SourceRuntime" to "python3.6-lib"
6. `rdk deploy YOUR_RULE_NAME --rdklib-layer-arn YOUR_RDKLIB_LAYER_ARN`
7. check lambda layers assigned - will find rdklib is assigned now

Expected results:
Steps 1-4 should complete successfully.

Workaround:
The only workaround I've found is to manually update the function after I've deployed my custom rule.
1. With your lambda using python3.9-lib, deploy your config rule via `rdk deploy`
2. Manually update the lambda layer either via the web-console or aws cli
`aws lambda update-function-configuration --function-name YOUR_FUNCTION_NAME --layers YOUR_RDKLIB_LAYER_ARN`

Info on python runtime support:
https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/

**Comment by kudosQUJO** [comment]
Any update on this? Now that python3.6 is no longer supported, the workaround is the only option atm.

**Comment by bmorrissirromb** [comment]
Thanks for pointing this one out. I think we've finally got a handle on the release process where we can keep up with deploying updated rdklib layers to all supported regions in a timely manner. I'm going to close this issue; `rdk` won't be quite ready to deploy using the latest layers yet, but the issue there is on the `rdk` side, not `rdklib`: `rdklib` has published the layers, `rdk` just needs to be told to use them.
