### ISSUE TITLE
Lambda Functions AssumeRole of the AWSServiceConfigRole will hit error

### ISSUE THREAD

**Issue by 4power** [awslabs/aws-config-rdklib#35]
By default, the Lambda Functions will try to AssumeRole of the AWSServiceConfigRole, if not pass the parameter of ExecutionRoleName,for some new user or lack experience user. the error message is not clear"An error occurred (AccessDenied) when calling the AssumeRole operation". can we prevent this error in  an elegant way?

**Comment by rickychau2780** [comment]
Thank you for the suggestion. We are working on the feature to not use Assume role and adding more detail on the error. Changes will be released by the end of next week

**Comment by mbeacom** [comment]
This is resolved in as of `0.2.3` via https://github.com/awslabs/aws-config-rdklib/pull/36.

Thanks again for the suggestion!
