### ISSUE TITLE
dumps stack trace in Evaluator.handle()

### ISSUE THREAD

**Issue by rchanter** [awslabs/aws-config-rdklib#4]
At line 38 of evaluator.py the call to ConfigRUle.evaluate_paramters is

`valid_rule_parameters = self.__rdk_rule.evaluate_parameters(rule_parameters)`

The function signature in the rule template (python3.6-lib) from the latest RDK (v0.7.3 via pip) is

`def evaluate_parameters(self, event, client_factory, rule_parameters):`

Editing the code of the generated rule to remove `event` and `client_factory` fixes this but I'm not sure if there are expectations elsewhere in the library code that these parameters should be provided. I'm just experimenting with a very minimal rule at the moment.

I'm using the rdklib public lambda layer from the serverless app repository

**Comment by jongogogo** [comment]
Good catch, for the moment you are good by just removing the variables. Working on the fix :)

**Comment by rickychau2780** [comment]
@rchanter I have fixed the template for python3.6-lib in RDK release 0.7.4. Please upgrade it and feel free to provide feedbacks again.

**Comment by jongogogo** [comment]
Resolving, feel free to re-open is any issue :)
